/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.daijishou.retroachievements

import kotlin.test.Test
import kotlin.test.assertTrue

class RetroAchievementsClientTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = RetroAchievementsClient()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
